# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - costprediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://insurancecost.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9584cfccf21043bfb83a265fafea59e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_60e8911247e249b6a2f25965f5f5f92f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: insurancecost.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9584cfccf21043bfb83a265fafea59e8 }}/insurancecostimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'costprediction'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_abf175adbfab4863b3ff57bb2204f231 }}
        images: 'insurancecost.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9584cfccf21043bfb83a265fafea59e8 }}/insurancecostimage:${{ github.sha }}'